- name: Test clusters
  hosts: localhost
  tasks:

    - name: Get a list of clusters with hosts
      clusters:
        action: list
        with_hosts: true
      register: list_clusters

    - name: List clusters with hosts
      debug:
        var: list_clusters

    - name: Delete a cluster
      clusters:
        action: delete
        cluster_id: "{{ my_cluster_id }}"
      register: delete_cluster
      when: my_cluster_id is defined

    - name: List deleted cluster
      debug:
        var: delete_cluster
      when: delete_cluster is defined

    - name: List the specified number of events for a given cluster ID
      clusters:
        action: list_events
        limit: "{{ event_limit }}" 
        cluster_id: "{{ my_cluster_id }}"
      register: events
      when: my_cluster_id is defined and event_limit is defined

    - name: Print the specified number of events for a given cluster ID
      debug:
        msg: "{{ events }}"
      when: event_limit is defined
